"""extend Account with SF-like fields

Revision ID: f2d84974f547
Revises: 17735437105a
Create Date: 2025-09-13 16:14:42.206188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d84974f547'
down_revision: Union[str, Sequence[str], None] = '17735437105a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_number', sa.String(length=50), nullable=True))
    op.add_column('accounts', sa.Column('employees', sa.Integer(), nullable=True))
    op.add_column('accounts', sa.Column('annual_revenue', sa.Integer(), nullable=True))
    op.add_column('accounts', sa.Column('rating', sa.String(length=20), nullable=True))
    op.add_column('accounts', sa.Column('ownership', sa.String(length=20), nullable=True))
    op.add_column('accounts', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'description')
    op.drop_column('accounts', 'ownership')
    op.drop_column('accounts', 'rating')
    op.drop_column('accounts', 'annual_revenue')
    op.drop_column('accounts', 'employees')
    op.drop_column('accounts', 'account_number')
    # ### end Alembic commands ###
